name: naxan_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  uuid: ^4.5.2

  firebase_core: ^4.2.1
  firebase_app_check: ^0.4.1+2
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  firebase_storage: ^13.0.4 # Payant :/ On passe sur mon serveur pour stocker des images.
  dio: ^5.9.0
  image_picker: ^1.2.0

  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0

  flutter_riverpod: ^3.0.3
  
  auto_route: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  auto_route_generator: ^10.2.5

flutter:
  uses-material-design: true
  assets:
    - .env